version: '3.9'

networks:
  proxy_overlay:
    external: true
      
volumes:
  geoserver-data:
  geo-db-data:

x-shared:
  common: &default-common
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

services:
  db:
    << : *default-common
    image: kartoza/postgis:${POSTGRES_VERSION}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - TIMEZONE=${POSTGRES_TIMEZONE}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"

  osm-geoserver:
    << : *default-common
    image: ttungbmt/geoserver:${GEOSERVER_VERSION}
    environment:
      - TOMCAT_EXTRAS=${TOMCAT_EXTRAS}
      - TOMCAT_USER=${TOMCAT_USER}
      - TOMCAT_PASSWORD=${TOMCAT_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - STABLE_EXTENSIONS=${GEOSERVER_STABLE_EXTENSIONS}
      - COMMUNITY_EXTENSIONS=${GEOSERVER_COMMUNITY_EXTENSIONS}
      - INITIAL_MEMORY=${GEOSERVER_INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${GEOSERVER_MAXIMUM_MEMORY}
      - SAMPLE_DATA=${GEOSERVER_SAMPLE_DATA}
      - XFRAME_OPTIONS=${XFRAME_OPTIONS}
      - ROOT_WEBAPP_REDIRECT=${ROOT_WEBAPP_REDIRECT}
      - ADDITIONAL_JAVA_STARTUP_OPTIONS="${ADDITIONAL_JAVA_STARTUP_OPTIONS}"
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - OSM_DB=${POSTGRES_DB}
      - OSM_SCHEMA=public
    volumes:
      - ${GEOSERVER_DATA}:/opt/geoserver/data_dir
    networks:
      - default
      - proxy_overlay
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u ${GEOSERVER_ADMIN_USER}:'${GEOSERVER_ADMIN_PASSWORD}' http://localhost:8080/geoserver/rest/about/version.xml"
      interval: 1m30s
      timeout: 10s
      retries: 3